//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHRIDB_DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TubeData
    {
        public System.Guid patientId { get; set; }
        public System.Guid regionId { get; set; }
        public string diagnosisKey { get; set; }
        public Nullable<int> blood { get; set; }
        public Nullable<int> sampleblood { get; set; }
        public Nullable<int> frozenTissue { get; set; }
        public Nullable<int> samplefrozenTissue { get; set; }
        public Nullable<int> waxBlock { get; set; }
        public Nullable<int> samplewaxBlock { get; set; }
        public Nullable<int> urine { get; set; }
        public Nullable<int> sampleurine { get; set; }
        public Nullable<int> dna { get; set; }
        public Nullable<int> sampledna { get; set; }
        public Nullable<int> stool { get; set; }
        public Nullable<int> samplestool { get; set; }
        public Nullable<int> sampleless { get; set; }
        public Nullable<int> pleuraleffusion { get; set; }
        public Nullable<int> samplepleuraleffusion { get; set; }
        public Nullable<int> CSF { get; set; }
        public Nullable<int> sampleCSF { get; set; }
        public Nullable<int> Ascites { get; set; }
        public Nullable<int> sampleAscites { get; set; }
        public Nullable<int> BoneMarrow { get; set; }
        public Nullable<int> sampleBoneMarrow { get; set; }
        public Nullable<int> Others_bilejuice_hair_saliva { get; set; }
        public int age { get; set; }
        public string endYear { get; set; }
        public System.Guid createUser { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.Guid> updateUser { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        public virtual Diagnosis Diagnosis { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Region Region { get; set; }
    }
}
