//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHRIDB_DAL.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TubeDataLog
    {
        public System.Guid hospitalId { get; set; }
        public string planKey { get; set; }
        public string patientKey { get; set; }
        public string regionKey { get; set; }
        public string diagnosisKey { get; set; }
        public string endYear { get; set; }
        public System.DateTime createDate { get; set; }
        public decimal age { get; set; }
        public System.DateTime LogDate { get; set; }
        public string gender { get; set; }
        public bool blood { get; set; }
        public bool frozenTissue { get; set; }
        public bool waxBlock { get; set; }
        public bool urine { get; set; }
        public bool urineClearLiquid { get; set; }
        public bool urinePellet { get; set; }
        public bool tissueDNA { get; set; }
        public bool tissueRNA { get; set; }
        public bool stool { get; set; }
        public bool stoolDNA { get; set; }
        public bool sampleless { get; set; }
        public bool pleuraleffusion { get; set; }
        public bool CSF { get; set; }
        public bool ascites { get; set; }
        public bool boneMarrow { get; set; }
        public bool serum { get; set; }
        public bool plasma { get; set; }
        public bool buffyCoat { get; set; }
        public bool wholeBlood { get; set; }
        public bool paraffinSection { get; set; }
        public bool bile { get; set; }
        public bool hair { get; set; }
        public bool saliva { get; set; }
        public bool bloodDNA { get; set; }
        public System.Guid createUser { get; set; }
        public bool CDM { get; set; }
        public bool questionnaire { get; set; }
        public bool CT { get; set; }
        public bool MRI { get; set; }
        public bool ultrasound { get; set; }
        public bool digit_pathology_image_data { get; set; }
        public bool DNA_WGS { get; set; }
        public bool DNA_WES { get; set; }
        public bool DNA_pannel { get; set; }
        public bool RNA { get; set; }
    }
}
